sudo: false

language: python

python:
  - 2.7
  - 3.4
  - 3.5
  - 3.6

matrix:
  fast_finish: true
  include:
    - python: 2.7
      os: linux
      language: generic
      env: TOXENV=py27
    - python: 3.6
      os: linux
      language: generic
      env: TOXENV=py36

install:
  - pip install -Ur requirements-test.txt
  - pip install -Ue .

script: tox -- --cov --no-cov-on-fail --cov-report=

after_success: codecov